
stages:
  - build_docs

pages:
  stage: build_docs
  image: continuumio/miniconda3:latest
  before_script:
    - apt-get update
    - apt-get install -y build-essential
    - conda update -n base conda
#    - conda config --set channel_priority strict
    - conda install -n base conda-libmamba-solver
    - conda config --set solver libmamba
    - conda env create -f environment.yml
    - source activate oss
    - pip install -e .
  script:
    - mkdir public
    - ls
    - cd docs
    - make html
    - ls
    - mv _build/html/ ../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH



