name: oss
channels:
  - astropy
  - conda-forge
  - defaults
dependencies:
  - python>3.11
  - astropy
  - black
  - bottleneck
  - cruft
  - docutils
  - lxml
  - matplotlib
  - numpy<2.0.1
  - pandas
  - pylint
  - pytest<8.0
  - pytest-cov
  - pytest-mock
  - pytest-doctestplus
  - sphinx
  - sphinx-automodapi
  - toml
